/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/kaoyan/admission-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admission Lines */
        get: operations["admission_lines_api_kaoyan_admission_lines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/ai-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Report */
        post: operations["ai_report_api_kaoyan_ai_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/cs408/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cs408 Conflicts */
        get: operations["cs408_conflicts_api_kaoyan_cs408_conflicts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/cs408/subject-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cs408 Subject Changes */
        get: operations["cs408_subject_changes_api_kaoyan_cs408_subject_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/cs408/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cs408 Units */
        get: operations["cs408_units_api_kaoyan_cs408_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/cs408/year-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cs408 Year Lines */
        get: operations["cs408_year_lines_api_kaoyan_cs408_year_lines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/enrollment-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enrollment Plans */
        get: operations["enrollment_plans_api_kaoyan_enrollment_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/heat-ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heat Ranking */
        get: operations["heat_ranking_api_kaoyan_heat_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/national-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** National Lines */
        get: operations["national_lines_api_kaoyan_national_lines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Programs */
        get: operations["programs_api_kaoyan_programs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provinces */
        get: operations["provinces_api_kaoyan_provinces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/rankings/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Program Ranking */
        get: operations["program_ranking_api_kaoyan_rankings_program_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kaoyan/reach-match-safety": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reach Match Safety */
        get: operations["reach_match_safety_api_kaoyan_reach_match_safety_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdmissionLineOut */
        AdmissionLineOut: {
            /** Degree Type */
            degree_type: string | null;
            /** Department */
            department: string | null;
            /** Foreign Language */
            foreign_language: number | null;
            /** Is 211 */
            is_211: boolean;
            /** Is 985 */
            is_985: boolean;
            /** Is Double First Class */
            is_double_first_class: boolean;
            /** Is Self Drawn */
            is_self_drawn: boolean;
            /** Political */
            political: number | null;
            /** Program Code */
            program_code: string | null;
            /** Program Name */
            program_name: string;
            /** Province */
            province: string | null;
            /** School Name */
            school_name: string;
            /** Source File */
            source_file: string;
            /** Subject One */
            subject_one: number | null;
            /** Subject Two */
            subject_two: number | null;
            /** Total Delta Raw */
            total_delta_raw: string | null;
            /** Total Score */
            total_score: number | null;
            /** Website */
            website: string | null;
            /** Year */
            year: number;
            /** Zone */
            zone: string | null;
        };
        /** AiReportDataRefOut */
        AiReportDataRefOut: {
            /** Band */
            band: string;
            /** Margin */
            margin: number;
            /** Reference Line */
            reference_line: number;
            /** School */
            school: string;
        };
        /** AiReportOut */
        AiReportOut: {
            /** Data Refs */
            data_refs: components["schemas"]["AiReportDataRefOut"][];
            /** Disclaimer */
            disclaimer: string;
            /** Generated By */
            generated_by: string;
            /** Sections */
            sections: components["schemas"]["AiReportSectionOut"][];
            /** Session Id */
            session_id: number;
            /** Style */
            style: string;
            /** Summary */
            summary: string;
        };
        /** AiReportRequest */
        AiReportRequest: {
            /** Is 211 */
            is_211?: boolean | null;
            /** Is 985 */
            is_985?: boolean | null;
            /** Program Code */
            program_code?: string | null;
            /** Program Name */
            program_name?: string | null;
            /** Province */
            province?: string | null;
            /** Score */
            score: number;
            /**
             * Style
             * @default neutral
             */
            style: string;
            /**
             * Window
             * @default 3
             */
            window: number;
            /** Year To */
            year_to?: number | null;
            /** Zone */
            zone?: string | null;
        };
        /** AiReportSectionOut */
        AiReportSectionOut: {
            /** Points */
            points: string[];
            /** Title */
            title: string;
        };
        /** Cs408ConflictOut */
        Cs408ConflictOut: {
            /** Action */
            action: string | null;
            /** Claims Json */
            claims_json: string | null;
            /** Field */
            field: string;
            /** New Value */
            new_value: string | null;
            /** Old Value */
            old_value: string | null;
            /** Reason */
            reason: string | null;
            /** School Name */
            school_name: string;
            /** Source File */
            source_file: string;
            /** Sources Json */
            sources_json: string | null;
            /** Status */
            status: string | null;
            /** Unit */
            unit: string;
        };
        /** Cs408SubjectChangeOut */
        Cs408SubjectChangeOut: {
            /** Effective Year */
            effective_year: string | null;
            /** New Subject */
            new_subject: string | null;
            /** Note */
            note: string | null;
            /** Old Subject */
            old_subject: string | null;
            /** School Name */
            school_name: string;
            /** Scope */
            scope: string;
            /** Source */
            source: string | null;
            /** Source File */
            source_file: string;
            /** Tier */
            tier: string | null;
        };
        /** Cs408UnitOut */
        Cs408UnitOut: {
            /** Admit Avg Raw */
            admit_avg_raw: string | null;
            /** Admit Avg Value */
            admit_avg_value: number | null;
            /** Admit Cnt Raw */
            admit_cnt_raw: string | null;
            /** Admit Cnt Value */
            admit_cnt_value: number | null;
            /** Admit Max */
            admit_max: number | null;
            /** Admit Max Raw */
            admit_max_raw: string | null;
            /** Admit Min */
            admit_min: number | null;
            /** Admit Min Raw */
            admit_min_raw: string | null;
            /** Ai Tag */
            ai_tag: string | null;
            /** Category */
            category: string | null;
            /** College */
            college: string;
            /** Direction */
            direction: string;
            /** Fill Raw */
            fill_raw: string | null;
            /** Heat Comp */
            heat_comp: number | null;
            /** Heat Net */
            heat_net: number | null;
            /** Kaoqing Url */
            kaoqing_url: string | null;
            /** Line2026 Raw */
            line2026_raw: string | null;
            /** Line 2026 Value */
            line_2026_value: number | null;
            /** Line Delta Raw */
            line_delta_raw: string | null;
            /** Nn 408 Avg */
            nn_408_avg: number | null;
            /** Nn 408 Avg Raw */
            nn_408_avg_raw: string | null;
            /** Nn Rate Raw */
            nn_rate_raw: string | null;
            /** Note */
            note: string | null;
            /** Plan2026 Raw */
            plan2026_raw: string | null;
            /** Plan2026 Value */
            plan2026_value: number | null;
            /** Province */
            province: string | null;
            /** Region */
            region: string | null;
            /** Retest Cnt Raw */
            retest_cnt_raw: string | null;
            /** Retest Cnt Value */
            retest_cnt_value: number | null;
            /** School Name */
            school_name: string;
            /** Scope */
            scope: string | null;
            /** Source File */
            source_file: string;
            /** Src Label */
            src_label: string | null;
            /** Subject Class */
            subject_class: string | null;
            /** Tier */
            tier: string | null;
            /** Wd Count */
            wd_count: number | null;
        };
        /** Cs408YearLineOut */
        Cs408YearLineOut: {
            /** College */
            college: string;
            /** Direction */
            direction: string;
            /** Line Raw */
            line_raw: string | null;
            /** Line Value */
            line_value: number | null;
            /** School Name */
            school_name: string;
            /** Source File */
            source_file: string;
            /** Year */
            year: number;
        };
        /** EnrollmentPlanOut */
        EnrollmentPlanOut: {
            /** City */
            city: string | null;
            /** Degree Type */
            degree_type: string | null;
            /** Department */
            department: string | null;
            /** Direction */
            direction: string | null;
            /** Enrollment Count */
            enrollment_count: number | null;
            /** Enrollment Note */
            enrollment_note: string | null;
            /** Enrollment Raw */
            enrollment_raw: string | null;
            /** Exam Method */
            exam_method: string | null;
            /** Exam Subjects */
            exam_subjects: string | null;
            /** Program Code */
            program_code: string | null;
            /** Program Name */
            program_name: string;
            /** Province */
            province: string | null;
            /** School Name */
            school_name: string;
            /** Source File */
            source_file: string;
            /** Study Mode */
            study_mode: string | null;
            /** Year */
            year: number;
            /** Zone */
            zone: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatRankingOut */
        HeatRankingOut: {
            /** Disclaimer */
            disclaimer: string;
            /** Excluded Missing */
            excluded_missing: number;
            /** Filters */
            filters: {
                [key: string]: string | null;
            };
            /** Rows */
            rows: components["schemas"]["HeatRankingRowOut"][];
            /** Sort */
            sort: string;
        };
        /** HeatRankingRowOut */
        HeatRankingRowOut: {
            /** Admit Cnt Value */
            admit_cnt_value: number | null;
            /** College */
            college: string;
            /** Direction */
            direction: string;
            /** Heat Comp */
            heat_comp: number | null;
            /** Heat Net */
            heat_net: number | null;
            /** Line 2026 Value */
            line_2026_value: number | null;
            /** Nn Rate Raw */
            nn_rate_raw: string | null;
            /** Province */
            province: string | null;
            /** Rank */
            rank: number;
            /** Region */
            region: string | null;
            /** School Name */
            school_name: string;
            /** Source File */
            source_file: string;
            /** Src Label */
            src_label: string | null;
            /** Subject Class */
            subject_class: string | null;
            /** Tier */
            tier: string | null;
            /** Wd Count */
            wd_count: number | null;
        };
        /** NationalLineOut */
        NationalLineOut: {
            /** Candidate Type */
            candidate_type: string;
            /** Category Kind */
            category_kind: string;
            /** Retrieved At */
            retrieved_at: string;
            /** Single 100 */
            single_100: number | null;
            /** Single Over100 */
            single_over100: number | null;
            /** Source Url */
            source_url: string;
            /** Subject */
            subject: string;
            /** Total Score */
            total_score: number | null;
            /** Year */
            year: number;
        };
        /** ProgramOptionOut */
        ProgramOptionOut: {
            /** Program Code */
            program_code: string;
            /** Program Name */
            program_name: string;
            /** School Count */
            school_count: number;
        };
        /** ProgramRankingOut */
        ProgramRankingOut: {
            /** Disclaimer */
            disclaimer: string;
            position: components["schemas"]["ScorePositionOut"] | null;
            /** Program Code */
            program_code: string | null;
            /** Program Name */
            program_name: string | null;
            /** Rows */
            rows: components["schemas"]["RankingRowOut"][];
            /** Year */
            year: number;
        };
        /** ProgramSearchOut */
        ProgramSearchOut: {
            /** Query */
            query: string | null;
            /** Rows */
            rows: components["schemas"]["ProgramOptionOut"][];
            /** Truncated */
            truncated: boolean;
        };
        /** ProvinceOut */
        ProvinceOut: {
            /** Name */
            name: string;
            /** School Count */
            school_count: number;
        };
        /** RankingRowOut */
        RankingRowOut: {
            /** Department */
            department: string | null;
            /** Foreign Language */
            foreign_language: number | null;
            /** Is 211 */
            is_211: boolean;
            /** Is 985 */
            is_985: boolean;
            /** Is Self Drawn */
            is_self_drawn: boolean;
            /** Political */
            political: number | null;
            /** Province */
            province: string | null;
            /** Rank */
            rank: number;
            /** School Name */
            school_name: string;
            /** Source File */
            source_file: string;
            /** Subject One */
            subject_one: number | null;
            /** Subject Two */
            subject_two: number | null;
            /** Total Score */
            total_score: number;
            /** Unit Count */
            unit_count: number;
            /** Zone */
            zone: string | null;
        };
        /** ReachMatchSafetyOut */
        ReachMatchSafetyOut: {
            /** Coverage Warning */
            coverage_warning: string | null;
            /** Disclaimer */
            disclaimer: string;
            /** Program Code */
            program_code: string | null;
            /** Program Name */
            program_name: string | null;
            /** Rows */
            rows: components["schemas"]["ReachMatchSafetyRowOut"][];
            /** Score */
            score: number;
            /** Window */
            window: number;
            /** Year To */
            year_to: number | null;
        };
        /** ReachMatchSafetyRowOut */
        ReachMatchSafetyRowOut: {
            /** Band */
            band: string;
            /** Department */
            department: string | null;
            /** Is 211 */
            is_211: boolean;
            /** Is 985 */
            is_985: boolean;
            /** Is Self Drawn */
            is_self_drawn: boolean;
            /** Lines */
            lines: components["schemas"]["ReachMatchSafetyYearLineOut"][];
            /** Margin */
            margin: number;
            /** Province */
            province: string | null;
            /** Reference Line */
            reference_line: number;
            /** School Name */
            school_name: string;
            /** Source File */
            source_file: string;
            /** Years Observed */
            years_observed: number;
            /** Zone */
            zone: string | null;
        };
        /** ReachMatchSafetyYearLineOut */
        ReachMatchSafetyYearLineOut: {
            /** Department */
            department: string | null;
            /** Total Score */
            total_score: number;
            /** Year */
            year: number;
        };
        /** ScorePositionOut */
        ScorePositionOut: {
            /** Provisional Rank */
            provisional_rank: number | null;
            /** Schools Passing */
            schools_passing: number;
            /** Score */
            score: number;
            /** Total Schools */
            total_schools: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admission_lines_api_kaoyan_admission_lines_get: {
        parameters: {
            query: {
                school: string;
                program?: string | null;
                degree_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmissionLineOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_report_api_kaoyan_ai_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cs408_conflicts_api_kaoyan_cs408_conflicts_get: {
        parameters: {
            query: {
                school: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cs408ConflictOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cs408_subject_changes_api_kaoyan_cs408_subject_changes_get: {
        parameters: {
            query: {
                school: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cs408SubjectChangeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cs408_units_api_kaoyan_cs408_units_get: {
        parameters: {
            query: {
                school: string;
                subject_class?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cs408UnitOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cs408_year_lines_api_kaoyan_cs408_year_lines_get: {
        parameters: {
            query: {
                school: string;
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cs408YearLineOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrollment_plans_api_kaoyan_enrollment_plans_get: {
        parameters: {
            query: {
                school: string;
                program?: string | null;
                study_mode?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentPlanOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heat_ranking_api_kaoyan_heat_ranking_get: {
        parameters: {
            query?: {
                sort?: string;
                province?: string | null;
                region?: string | null;
                subject_class?: string | null;
                tier?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatRankingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    national_lines_api_kaoyan_national_lines_get: {
        parameters: {
            query?: {
                year?: number | null;
                subject?: string | null;
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NationalLineOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    programs_api_kaoyan_programs_get: {
        parameters: {
            query?: {
                query?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provinces_api_kaoyan_provinces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceOut"][];
                };
            };
        };
    };
    program_ranking_api_kaoyan_rankings_program_get: {
        parameters: {
            query: {
                year: number;
                program_code?: string | null;
                program_name?: string | null;
                score?: number | null;
                zone?: string | null;
                is_985?: boolean | null;
                is_211?: boolean | null;
                is_self_drawn?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramRankingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reach_match_safety_api_kaoyan_reach_match_safety_get: {
        parameters: {
            query: {
                score: number;
                year_to?: number | null;
                window?: number;
                program_code?: string | null;
                program_name?: string | null;
                province?: string[] | null;
                zone?: string[] | null;
                is_985?: boolean | null;
                is_211?: boolean | null;
                is_self_drawn?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReachMatchSafetyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
